### ISSUE TITLE
Forgotten c_best update in lazy_shortening of rrt_star_bid_h

### ISSUE THREAD

**Issue by tahsinkose** [motion-planning/rrt-algorithms#19]
Hi there,

I was producing metrics with these algorithms and figured out this problem which results in an infinite loop in Heuristicized Bidirectional RRT*. Whenever it shortens the path, the best cost should be adapted accordingly after the [line](https://github.com/motion-planning/rrt-algorithms/blob/a403f34150e765be38b349329d91642f347cf280/src/rrt/rrt_star_bid_h.py#L109):
`self.sigma_best = self.sigma_best[:min(a, b) + 1] + self.sigma_best[max(a, b):]`

So we need to simply iterate over the sigma_best and compute new cost after the line above. I'm planning to submit a minor PR for that in this evening.

**Comment by SZanlongo** [comment]
Closed along with #23.
