### ISSUE TITLE
Help with this errror

### ISSUE THREAD

**Issue by michaelchi08** [motion-planning/rrt-algorithms#22]
michael@michael:~/dev/rrt-algorithms/examples/rrt$ python3 rrt_2d.py 
Traceback (most recent call last):
  File "rrt_2d.py", line 5, in <module>
    from src.rrt.rrt import RRT
ModuleNotFoundError: No module named 'src'

Hello,
Can someone please help me with this error? i'm running this on ubuntu 18.04.

Thanks

**Comment by SZanlongo** [comment]
Which version of Python are you on?

It sounds like you might be on a version prior to 3.3.
Each directory should have a file named `__init__.py`

For more information, try reading: [Traps for the Unwary in Python’s Import System](http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html).

**Comment by n1try** [comment]
I got the same problem. Using Python 3.6.8.

**Comment by n1try** [comment]
Solved by doing `export PYTHONPATH="$(pwd)"` in project root.

**Comment by kctoayo88** [comment]
@muety Hello, I met the same issue. Could you specify how did you solve this problem?

**Comment by kctoayo88** [comment]
It is solved.

Add the following lines before the 'import'.
```
import sys
sys.path.append('./rrt_algorithms')

import numpy as np

from src.rrt.rrt_star import RRTStar
from src.search_space.search_space import SearchSpace
from src.utilities.plotting import Plot
```
