### ISSUE TITLE
Unpredictable Obstacles

### ISSUE THREAD

**Issue by jackson2213** [motion-planning/rrt-algorithms#26]
Hi , i want to add triangle Obstacles, not rectangle , i don't know how to change the code.  I look forward to hearing from you. Thakns!

**Comment by SZanlongo** [comment]
Hi @jackson2213; this project uses the rtree library to maintain a [spatial index](https://rtree.readthedocs.io/en/latest/tutorial.html#creating-an-index). I believe this is restricted to objects with rectangular shapes, so a triangle would not be possible.

A workaround might be to approximate the triangle using multiple smaller rectangles, which could then be inserted into the obstacle region and used as a proxy.
