### ISSUE TITLE
The length of extending step 

### ISSUE THREAD

**Issue by kctoayo88** [motion-planning/rrt-algorithms#27]
Hello,

I would like to know how to adjust the length of extending step when the RRT is executing.
I saw you wrote this line in the readme, but I can't find the parameter in programs.

> q: Distance away from existing vertices to probe.

Hope you can give me some tips, thanks!

**Comment by SZanlongo** [comment]
Hi @kctoayo88. The best way to ensure you understand how that works is probably by following along with one if the examples.

`Q` is a list of tuples `q` indicating that q[0] edges of length q[1] should be added. This choice was made to allow for easily trying different amounts of different-length edges. For example, if we set `Q = [[4, 1], [2, 8]]`, this would attempt to grow 4 edges of length 1, and 2 edges of length 8.

Starting with the `rrt_2d.py` example, we set the length of new edges in `Q = np.array([(8, 4)])`, corresponding to trying to grow 8 edges of length 4 on each iteration. Next, the search is done in `rrt.py`, where you can see the looping over different edge combinations within `Q`. For each of the tuples, it calls `new_and_near`, with an edge length from the tuple.

Hope this helps.

**Comment by kctoayo88** [comment]
Hello @SZanlongo, 

Thanks for your reply, it's really helpful to me.
I could understand and handle it now.

Unfortunately, I got another problem when I run the rrt_star_2d.py program.
I always defined the obstacles, init and goal position by myself in this program.
However, the program got some error in some specific cases.
I guessed that the reason of error occurring is related to obstacles and init, goal setting.
Hope you could help me solve this. 
![error](https://user-images.githubusercontent.com/33343560/79955452-66620880-84b1-11ea-880c-5942d5bff8b9.jpg)

**Comment by SZanlongo** [comment]
Seems like you hit an edge case. I've pushed what should be a fix to develop. Let me know if that works.

**Comment by kctoayo88** [comment]
@SZanlongo ,

Thank you for your helps.
The change solve the problem perfectly and work like a charm.
