### ISSUE TITLE
unable to connect to the goal

### ISSUE THREAD

**Issue by coderpracticer** [motion-planning/rrt-algorithms#32]
Hi,i get this when i run the code.Has someone meet the same question?
Checking if can connect to goal at 9 samples
Could not connect to goal
Checking if can connect to goal at 38 samples
Can connect to goal

**Comment by SZanlongo** [comment]
I'm not certain I understand what the question is.

The output you are seeing is a status of the sampling (for a better understanding of the underlying algorithms, please see [Steven LaValle's site](https://lavalle.pl/rrtpubs.html).
Every time a new edge is added, there is a probability to check whether the goal can be reached - shown by `Checking if can connect to goal at $n$ samples`. Often towards the beginning of the sampling, it will not be possible, as indicated by `Could not connect to goal`. If a connection _is_ possible, then you will see the final line `Can connect to goal`.

**Comment by steven1526** [comment]
I meet the same question and the final line is 'can connect to goal'.But why python  only give this answer?
