### ISSUE TITLE
Which article are ideas of RRT* using R-tree from?

### ISSUE THREAD

**Issue by qlchen2117** [motion-planning/rrt-algorithms#35]
Can someone tell me where this idea comes from? Thanks.

**Comment by SZanlongo** [comment]
I'm not sure of the original source, this is the oldest publication I could find that mentioned r-trees and RRT, though it doesn't seem to be the originator of the idea.

Pan, Jia, Christian Lauterbach, and Dinesh Manocha. "[Efficient nearest-neighbor computation for GPU-based motion planning.](https://gamma.cs.unc.edu/gplanner/IROS.pdf)" 2010 IEEE/RSJ International Conference on Intelligent Robots and Systems. IEEE, 2010.
